[pytest]
asyncio_mode = auto
testpaths = app/tests
addopts =
    --cov=app
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-fail-under=95
    -v

[coverage:run]
omit =
    app/tests/*
    app/core/logger.py
